spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/collaborationTool
    username: postgres
    password: ${DB_PASSWORD}

server:
  port: 8082

alibaba:
  cloud:
    oss:
      endpoint: https://oss-eu-west-1.aliyuncs.com
      access-key-id: ${ALIBABA_OSS_KEY}
      access-key-secret: ${ALIBABA_OSS_SECRET}
      bucket-name: jagarage

app:
  message: "This is the Development environment"

jwt:
  secret: ${JWT_SECRET}