spring:
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  data:
    redis:
      url: ${REDIS_URL}
      lettuce:
        pool:
          enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/collaborationTool
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

brevo:
  api-key: ${BREVO_API_KEY}
  from-email: ${BREVO_FROM_EMAIL}
  from-name: ${BREVO_FROM_NAME}

server:
  port: 8082

alibaba:
  cloud:
    oss:
      endpoint: https://oss-eu-west-1.aliyuncs.com
      access-key-id: ${ALIBABA_OSS_KEY}
      access-key-secret: ${ALIBABA_OSS_SECRET}
      bucket-name: jagarage

app:
  message: "This is the Development environment"

jwt:
  secret: ${JWT_SECRET}